version: '3.9'


services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    environment:
      - NGINX_DOMAIN=${DOMAIN}
    volumes:
      - ${BACK_PATH}:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/templates:/etc/nginx/templates
    depends_on:
      - back
  back:
    build:
      context: ${BACK_PATH}
    depends_on:
      - pg
      - redis
      - elasticsearch
    volumes:
      - ${BACK_PATH}:/var/www
  pg:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_SHARED_BUFFERS: 1GB
      POSTGRES_WORK_MEM: 128MB
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pg/data:/var/lib/postgresql/data
      - ./pg/etc:/data
  redis:
    image: redis
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data
  elasticsearch:
    image: elasticsearch:8.10.1
    environment:
      node.name: elasticsearch
      discovery.type: single-node
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      xpack.security.enabled: false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/hunspell:/usr/share/elasticsearch/config/hunspell

volumes:
  elasticsearch_data:
    driver: local